defaults: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 127.0.0.1
  username: 
  password: 

development: &DEV
  <<: *defaults
  database: wildthing_development

test: &TEST
  <<: *defaults
  database: wildthing_test

production:
  <<: *defaults
  database: wildthing_production